# Generated by Django 4.0.6 on 2022-07-05 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableDateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DateSubscriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morning', models.BooleanField()),
                ('afternoon', models.BooleanField()),
                ('comment', models.TextField(blank=True)),
                ('datetime_creation', models.DateTimeField(auto_now_add=True)),
                ('datetime_modification', models.DateTimeField(auto_now=True)),
                ('subscription_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.availabledatemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
                ('track_coordinates', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('locality', models.CharField(max_length=40)),
                ('student_phone', models.CharField(blank=True, max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.schoolmodel')),
                ('subscription', models.ManyToManyField(blank=True, to='subscription.datesubscriptionmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StopModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time_morning', models.TimeField()),
                ('time_afternoon', models.TimeField()),
                ('place', models.CharField(max_length=500)),
                ('picture', models.ImageField(upload_to='places')),
                ('coordinates', models.JSONField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.trackmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.schoolmodel')),
                ('subscription', models.ManyToManyField(blank=True, to='subscription.datesubscriptionmodel')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.trackmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
